version: 2
updates:
    - package-ecosystem: "pip" # See documentation for possible values
      directory: "/" # Location of package manifests
      target-branch: "main"
      schedule:
        interval: "weekly"
      labels:
        - "backend/dependencies"

    - package-ecosystem: "npm"
      directory: "/frontend"
      target-branch: "main"
      schedule:
        interval: "weekly"
        day: "sunday"
      labels:
        - "frontend/dependencies"
