version: '3.4'

services:
  web:
    container_name: erpt.backend.application
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    image: erpt
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:${APP_PORT:-8080}"
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8080}:8080"

  mysql:
    container_name: erpt.data.db
    image: mysql:8.0
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  static_volume:
  media_volume:
  db_data:
