# Generated by Django 4.0.6 on 2022-07-21 12:11

from django.db import migrations
from api.models import Role, Permission, RolePermission


def fillBaseRoles(app, schema_editor):
    Role(name="Admin", nick="sys.admin", role_class="Administración").save()
    Role(name="Sistemas", nick="sys.admin", role_class="Administración").save()


def fillBasePermissions(app, schema_editor):
    perms = [
        {"codename": "View role permission", "name": "view_permission"},
        {"codename": "Add role permission", "name": "add_permission"},
        {"codename": "Change role permission", "name": "change_permission"},
        {"codename": "Delete role permission", "name": "delete_permission"},
        {"codename": "Change user password", "name": "change_password"},
        {"codename": "Change user email", "name": "change_email"},
        {"codename": "View user data", "name": "view_user"},
        {"codename": "Create a new user", "name": "add_user"},
        {"codename": "Modify user data", "name": "modify_user"},
        {"codename": "Modify user data", "name": "change_user"},
        {"codename": "Soft delete user", "name": "delete_user"},
        {"codename": "Create an employee", "name": "add_employee"},
        {"codename": "View employee info", "name": "view_employee"},
        {"codename": "Add a new employee", "name": "add_employee"},
        {"codename": "Change employee data", "name": "change_employee"},
        {"codename": "Soft delete an employee", "name": "delete_employee"},
        {"codename": "Create a new role", "name": "add_role"},
        {"codename": "Edit a role", "name": "change_role"},
        {"codename": "View a role info", "name": "view_role"},
        {"codename": "Soft delete a role", "name": "delete_role"},
    ]
    admin_roles = Role.objects.filter(nick="sys.admin")
    for perm in perms:
        permission = Permission(**perm)
        permission.save()
        for admin_role in admin_roles:
            RolePermission(permission=permission, role=admin_role).save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fillBaseRoles),
        migrations.RunPython(fillBasePermissions),
    ]
