# Generated by Django 4.0.6 on 2022-07-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermission',
            table='user_permissions',
        ),
    ]
