# Generated by Django 4.1 on 2022-09-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_base_data"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InventoryModel",
            new_name="Inventory",
        ),
        migrations.RenameModel(
            old_name="WharehouseModel",
            new_name="Warehouse",
        ),
        migrations.RenameModel(
            old_name="WharehouseTransactionModel",
            new_name="WarehouseTransaction",
        ),
        migrations.RenameModel(
            old_name="WhTransactionDetailsModel",
            new_name="WhTransactionDetails",
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="wharehouse",
            new_name="warehouse",
        ),
        migrations.RenameField(
            model_name="orderrequest",
            old_name="wharehouse",
            new_name="warehouse",
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="wharehouse",
            new_name="warehouse",
        ),
        migrations.RenameField(
            model_name="warehousetransaction",
            old_name="wharehouse_destiny",
            new_name="warehouse_destiny",
        ),
        migrations.RenameField(
            model_name="warehousetransaction",
            old_name="wharehouse_origin",
            new_name="warehouse_origin",
        ),
        migrations.AlterModelTable(
            name="warehouse",
            table="warehouse",
        ),
        migrations.AlterModelTable(
            name="warehousetransaction",
            table="warehouse_transaction",
        ),
    ]
