# Generated by Django 4.1 on 2022-12-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_base_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attributes",
                to="api.productvariant",
            ),
        ),
    ]
