# Generated by Django 4.1.1 on 2022-09-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_inventorymodel_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
