# Generated by Django 4.0.6 on 2022-12-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_productattribute_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedetail",
            name="item",
        ),
        migrations.RemoveField(
            model_name="whtransactiondetails",
            name="item",
        ),
        migrations.AddField(
            model_name="productstockwarehouse",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.employee",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedetail",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedetail",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="whtransactiondetails",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="whtransactiondetails",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="whtomasfisicas",
            name="novedad",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="WhTomasFisicasDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("novedad", models.CharField(max_length=300)),
                ("new_stock", models.PositiveIntegerField()),
                ("previous_stock", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.product"
                    ),
                ),
                (
                    "toma_fisica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.whtomasfisicas",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "tomas_fisicas_details",
            },
        ),
        migrations.CreateModel(
            name="TransactionStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.employee",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.status"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.warehousetransaction",
                    ),
                ),
            ],
            options={
                "db_table": "transaction_status",
            },
        ),
    ]
