# Generated by Django 4.1.1 on 2022-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.CharField(default=2, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
