# Generated by Django 4.1 on 2022-10-09 21:18

from django.db import migrations

from api.models.common import Status


def create_base_statuses(a, b):
    statuses = [
        ('active', 'active status'),
        ('enabled', 'enabled status'),
        ('unavailable', 'enabled status'),
        ('deleted', 'deleted status'),
        ('removed', 'removed status'),
        ('inactive', 'inactive status'),
        ('obsolete', 'obsolete status'),
        ('purge', 'purged status')
    ]
    for status in statuses:
        Status(
            name=status[0], description=status[1]
        ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_status_created_by"),
    ]

    operations = [
        migrations.RunPython(create_base_statuses)
    ]
