# Generated by Django 4.1.2 on 2022-12-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_purchasedetail_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="orderrequestdetail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="orderrequestdetail",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ordered_on",
                to="api.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
