# Generated by Django 4.0.6 on 2022-12-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_purchasedetail_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='img_details',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='purchase',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reference',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='PurchaseChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_details', models.CharField(max_length=255, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.invoice')),
                ('purchase_header', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.purchase')),
            ],
            options={
                'db_table': 'purchase_child',
            },
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase_child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.purchasechild'),
            preserve_default=False,
        ),
    ]
