# Generated by Django 4.1 on 2022-10-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_status_fill"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="status",
            index=models.Index(fields=["name"], name="status_name_6cc223_idx"),
        ),
    ]
