# Generated by Django 4.0.6 on 2022-12-15 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orderrequest_id_alter_orderrequestdetail_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='aproved_at',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='img_details',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='provider',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='revised_by',
            field=models.OneToOneField(db_column='revised_by', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='revised_by', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reference',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='id',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasestatus',
            name='id',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PurchaseChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('img_details', models.CharField(max_length=255, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.invoice')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.provider')),
                ('purchase_header', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.purchase')),
            ],
            options={
                'db_table': 'purchase_child',
            },
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase_child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.purchasechild'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='purchasedetail',
            unique_together={('product', 'variant', 'purchase_child')},
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='purchase',
        ),
    ]
