# Generated by Django 4.1.4 on 2022-12-26 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_aproved_at_purchase_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="status",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="provider",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
