# Generated by Django 4.1.1 on 2022-10-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='codigo',
        ),
    ]
