# Generated by Django 4.1 on 2022-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_status_status_name_6cc223_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmetadata",
            name="value",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["name"], name="warehouse_name_d8d877_idx"),
        ),
    ]
