# Generated by Django 4.1.1 on 2022-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_item_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.CharField(default=None, max_length=16, unique=True),
        ),
    ]
