# Generated by Django 4.1 on 2022-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_itemmetadata_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrequest",
            name="comment",
            field=models.CharField(
                default="", help_text="Comentario adicional al pedido", max_length=512
            ),
        ),
    ]
