# Generated by Django 4.1.4 on 2022-12-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_provider_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.employee",
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="deleted_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.employee",
                verbose_name="Deleted by",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.employee",
                verbose_name="Updated by",
            ),
        ),
    ]
