# Generated by Django 4.1 on 2022-10-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_orderrequest_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="codename",
            field=models.CharField(
                default="",
                help_text="The codename or identifier for the item",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["codename"], name="items_codenam_c40900_idx"),
        ),
    ]
