# Generated by Django 4.0.6 on 2023-01-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_provider_created_by_provider_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whtomasfisicasdetails',
            name='acepted',
            field=models.CharField(choices=[('PA', 'Pendiente aprobación'), ('AP', 'Aceptado'), ('NA', 'No Aceptado')], default='PA', max_length=6),
        ),
        migrations.AddField(
            model_name='whtomasfisicasdetails',
            name='acepted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
