# Generated by Django 4.0.6 on 2023-01-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_whtomasfisicasdetails_acepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='revised_by',
            field=models.ForeignKey(db_column='revised_by', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='revised_by', to='api.employee'),
        ),
    ]
