# Generated by Django 4.1 on 2022-10-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_item_codename_item_items_codenam_c40900_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="codename",
            field=models.CharField(
                help_text="The codename or identifier for the item",
                max_length=128,
                unique=True,
            ),
        ),
    ]
