# Generated by Django 4.1 on 2023-01-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_orderrequest_revised_by"),
        ("api", "0010_productvariant_ean_productvariant_upc"),
    ]

    operations = []
