# Generated by Django 4.1 on 2022-10-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_item_codigo"),
        ("api", "0010_alter_item_codename"),
    ]

    operations = []
