# Generated by Django 4.1.1 on 2022-10-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_codigo'),
        ('api', '0010_alter_item_codename'),
    ]

    operations = [
    ]
