# Generated by Django 4.1.1 on 2022-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_0008_item_codigo_0010_alter_item_codename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_codenam_c40900_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='client',
            name='number_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='itemmetadata',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
