# Generated by Django 4.1.5 on 2023-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20230119_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='whtomasfisicasdetails',
            name='acepted_comment',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
