# Generated by Django 4.1 on 2022-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_merge_20221025_0432"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="items_codenam_c40900_idx",
        ),
        migrations.AlterField(
            model_name="itemmetadata",
            name="value",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
