# Generated by Django 4.1.2 on 2022-10-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_item_items_codenam_c40900_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="number_id",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="storage/public/item"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="deleted_by",
            field=models.ForeignKey(
                db_column="deleted_by",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="remover",
                to="api.employee",
            ),
        ),
    ]
