# Generated by Django 4.1.2 on 2022-10-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_client_number_id_alter_item_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="latitude",
            field=models.DecimalField(decimal_places=17, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="longitude",
            field=models.DecimalField(decimal_places=17, max_digits=25, null=True),
        ),
    ]
