# Generated by Django 4.1.2 on 2022-10-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_provider_latitude_alter_provider_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="document_path",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
