# Generated by Django 4.1.2 on 2022-11-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_provider_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sequence',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='emission',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit_note',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.creditnote'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='return_deadline',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_code',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_details', to='api.invoice'),
        ),
    ]
