# Generated by Django 4.1.2 on 2022-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_provider_document_path"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(
                fields=["bussiness_name"], name="provider_bussine_c6ea86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(
                fields=["document_path"], name="provider_documen_3d7fa2_idx"
            ),
        ),
    ]
