# Generated by Django 4.1 on 2022-11-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_provider_provider_bussine_c6ea86_idx_and_more"),
        ("api", "0016_sequence_invoice_emission_alter_invoice_code_and_more"),
    ]

    operations = []
