# Generated by Django 4.1.2 on 2022-11-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_sequence_invoice_emission_orderrequest_approved_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderrequest",
            old_name="approved_at",
            new_name="revised_at",
        ),
        migrations.RenameField(
            model_name="orderrequest",
            old_name="approved_by",
            new_name="revised_by",
        ),
    ]
