# Generated by Django 4.1.2 on 2022-11-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_sequence_invoice_emission_alter_invoice_code_and_more"),
        ("api", "0019_rename_approved_at_orderrequest_revised_at_and_more"),
    ]

    operations = []
