# Generated by Django 4.1 on 2022-11-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_invoice_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created_by",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="api.gender"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
