# Generated by Django 4.1 on 2022-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_employee_created_by_employee_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="address",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
