# Generated by Django 4.0.6 on 2022-11-24 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_provider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='aproved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.invoice'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.orderrequest'),
        ),
        migrations.CreateModel(
            name='WhTomasFisicas',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novedad', models.CharField(blank=True, max_length=300)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.warehouse')),
            ],
            options={
                'db_table': 'tomas_fisicas',
            },
        ),
    ]
