# Generated by Django 4.1.3 on 2022-11-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_provider_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
