# Generated by Django 4.0.6 on 2022-12-03 02:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_product_productvariant_variantmeta_productproviders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productvariant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.warehouse')),
            ],
            options={
                'db_table': 'product_inventory',
            },
        ),
    ]
