# Generated by Django 4.1 on 2022-12-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_employee_address"),
        ("api", "0026_product_productvariant_variantmeta_productproviders_and_more"),
    ]

    operations = []
