# Generated by Django 4.0.6 on 2022-12-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_inventoryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whtomasfisicas',
            name='novedad',
            field=models.TextField(blank=True),
        ),
    ]
