# Generated by Django 4.1 on 2022-12-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_employee_created_by"),
        ("api", "0027_merge_20221203_1120"),
    ]

    operations = []
