# Generated by Django 4.1 on 2022-12-04 03:29

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_merge_20221203_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.utils.PathAndRename("products")
            ),
        ),
    ]
