# Generated by Django 4.1 on 2022-12-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_product_is_active_productvariant_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attributes",
                        to="api.productvariant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attributes",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attributes",
            },
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("charfield", models.CharField(blank=True, max_length=128, null=True)),
                ("intfield", models.IntegerField(null=True)),
                (
                    "decimalfield",
                    models.DecimalField(decimal_places=5, max_digits=65, null=True),
                ),
                ("floatfield", models.FloatField(null=True)),
                ("boolfield", models.BooleanField(default=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.employee",
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.employee",
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.employee",
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "db_table": "api_test_table",
            },
        ),
        migrations.RemoveField(
            model_name="variantmeta",
            name="variant",
        ),
        migrations.DeleteModel(
            name="ProductMeta",
        ),
        migrations.DeleteModel(
            name="VariantMeta",
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(fields=["name"], name="product_att_name_8a11ad_idx"),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(fields=["value"], name="product_att_value_ae3010_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("option", "name")},
        ),
    ]
