# Generated by Django 4.1 on 2022-12-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_productattribute_testmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True, default="field_value", max_length=128, null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="childs",
                        to="api.testmodel",
                    ),
                ),
            ],
        ),
    ]
