// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Col: typeof import('./components/grid/Col.vue')['default']
    DrawerMenu: typeof import('./components/custom/DrawerMenu.vue')['default']
    DrawerMenuItem: typeof import('./components/custom/DrawerMenuItem.vue')['default']
    EButton: typeof import('./components/custom/EButton.vue')['default']
    ECard: typeof import('./components/custom/ECard.vue')['default']
    ECol: typeof import('./components/custom/ECol.vue')['default']
    EmployeeCardItem: typeof import('./components/models/EmployeeCardItem.vue')['default']
    EOverlay: typeof import('./components/custom/EOverlay.vue')['default']
    ERow: typeof import('./components/custom/ERow.vue')['default']
    ETab: typeof import('./components/holders/ETab.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputText: typeof import('./components/custom/InputText.vue')['default']
    ListBox: typeof import('./components/custom/ListBox.vue')['default']
    LoadingBar: typeof import('./components/custom/LoadingBar.vue')['default']
    ModalDialog: typeof import('./components/custom/ModalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./components/grid/Row.vue')['default']
    Table: typeof import('./components/holders/Table.vue')['default']
    TextArea: typeof import('./components/custom/TextArea.vue')['default']
    Title: typeof import('./components/custom/Title.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserCardItem: typeof import('./components/models/UserCardItem.vue')['default']
    WaitOverlay: typeof import('./components/custom/WaitOverlay.vue')['default']
  }
}
