name: Deploy to production

on:
  push:
    branches:
      - main
      
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: Stablish connection with ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{secrets.PORT }}
            script: whoami
        - name: Sync codebase (backend)
          run: echo 'Sync'
        - name: Install backend deps
          run: echo 'Install backend'
        - name: Compile frontend
          run: echo 'Compile front'
        - name: Upload static files
          run: echo 'Upload'
